-- AlterTable
ALTER TABLE `orderitem` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `merchantId` VARCHAR(191) NULL,
    ADD COLUMN `subtotal` DOUBLE NULL,
    MODIFY `name` VARCHAR(191) NULL;
